### ISSUE TITLE
releaseKey=461814

### ISSUE THREAD

**Issue by hopla** [shanselman/SmallestDotNet#103]
Just got an error message that the .NET checker was not able to determine the exact version. The reported releaseKey=461814.
This should have been fixed according to issue #99 .

**Comment by HaydenMacdonaldRG** [comment]
there was a typo in 4d01bfedf625ddbb1739967b763b77cc80600b9d
On line 62 it says 491814, but it should be 461814

**Comment by grhm** [comment]
Yeah. Mea culpa.  Created a PR to fix this.
