### ISSUE TITLE
Handle unknown releases better

### ISSUE THREAD

**Issue by binki** [shanselman/SmallestDotNet#41]
I have .net-4.6 and when I run the tool it just reports that I have .net-4.5. This is misleading and unhelpful because it suggests I have something that is older than .net-4.5.2. Instead, it should say that it scanned “381029” and doesn’t know about it yet.

**Comment by marcosnz** [comment]
@binki are the changes in my pull request OK?

**Comment by binki** [comment]
It’s better, but it is hard to find the link being referenced by the text “Please log an issue using the link at the bottom of the page including this information”—the link should probably just be placed like `Please <a href="https://github.com/shanselman/SmallestDotNet/issues/">log an issue</a> including this information`.

**Comment by marcosnz** [comment]
Done

**Comment by binki** [comment]
Nice, that handles much more gracefully than the currently-hosted code. @shanselman, please consider merging this.
