### ISSUE TITLE
Handle Variable Font Sizes Better.

### ISSUE THREAD

**Issue by mrjava66** [shanselman/SmallestDotNet#45]
I have a larger than normal setting on my font.  These means I cannot see all the output.

![untitled](https://cloud.githubusercontent.com/assets/8010086/7262021/d9ada56e-e83b-11e4-9667-548bbf7d2d12.png)

I think you detect the font size, or just allow the screen to be made bigger, or just make the screen bigger.

**Comment by marcosnz** [comment]
I think you are using Raymondcc .NET Detector (https://www.raymond.cc/blog/).
That is different to the website that this repository is for - http://smallestdotnet.com/
