### ISSUE TITLE
Edge (aka Spartan) called Chrome

### ISSUE THREAD

**Issue by marcosnz** [shanselman/SmallestDotNet#47]
When I browse to site with latest build of Windows 10 Edge browser the site says "Looks like you're running Chrome..."
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0

When running from IE in Windows 10 it says I have 4.5 because the use agent is saying NT 6.3
Full user agent:
Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; MALCJS; rv:11.0) like Gecko

**Comment by marcosnz** [comment]
@shanselman http://hanselstorage.blob.core.windows.net/blog/CheckForDotNet45.exe is still returning a URL with realversion rather than releaseKey. I assume it hasn't been updated to latest binary?

**Comment by shanselman** [comment]
Looks like it. I'll see if I can update it now.

**Comment by shanselman** [comment]
Ok, updated. It should propagate in a day or so.

**Comment by marcosnz** [comment]
Thanks!

**Comment by marcosnz** [comment]
Umm.... I'm still getting old version.

**Comment by shanselman** [comment]
Weird. I'm not. Check your cache. Maybe Save As? What size is yours? Mine
is 7168 bytes.

On Mon, May 11, 2015 at 9:16 PM, Mark <notifications@github.com> wrote:

> Umm.... I'm still getting old version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shanselman/SmallestDotNet/issues/47#issuecomment-101124482>
> .
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by marcosnz** [comment]
Ah, yep, must be cache. Different browser worked fine. Tried "Save as" on original browser and it also worked (but a direct download still doesn't). Sorry for wasting your time.

**Comment by shanselman** [comment]
Not a waste at all! Thanks!

On Tue, May 12, 2015 at 8:25 PM, Mark <notifications@github.com> wrote:

> Ah, yep, must be cache. Different browser worked fine. Tried "Save as" on
> original browser and it also worked (but a direct download still doesn't).
> Sorry for wasting your time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shanselman/SmallestDotNet/issues/47#issuecomment-101495081>
> .
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes
