### ISSUE TITLE
releaseKey=393292 not recognized

### ISSUE THREAD

**Issue by binki** [shanselman/SmallestDotNet#49]
I was sent here by http://smallestdotnet.com/?releaseKey=393292

> We Found .NET!
> 
> The .Net Checker application determined that you have 4.6 Preview or greater on your machine. The application was not able to determine the exact version you have. Please [log an issue](https://github.com/shanselman/SmallestDotNet/issues/) including this information: releaseKey=393292 so we can get it exact in the future.

**Comment by marcosnz** [comment]
Thanks for taking the time to create an issue! 
Can you tell me what OS this is on? If Win 10 what build? Any other information that might help me to track down the .Net version would be helpful!

**Comment by binki** [comment]
It’s Windows 10 Technical Preview build 10130. Not sure myself how to best identify the framework version. devenv says it’s running on .net 4.6.00076. System Information -> System Summary -> Software Environment -> Loaded Modules says `clr` is version 4.6.76.2. There a better place to look for this information or a way to find official names for these things?

**Comment by marcosnz** [comment]
Awesome, thanks, I will try and find out some more info and will update here
