### ISSUE TITLE
Update for .net 4.6RTM

### ISSUE THREAD

**Issue by marcosnz** [shanselman/SmallestDotNet#52]
4.6 is [now RTM](http://weblogs.asp.net/scottgu/released-today-visual-studio-2015-asp-net-4-6-asp-net-5-ef-7-previews). The registry  release key is 393297.
I will work on a PR

**Comment by bryanfree66** [comment]
Can I take this one?

**Comment by rpirritano** [comment]
I am first time contributor, is this still available?  If so I can take it?
