### ISSUE TITLE
releaseKey=393295 

### ISSUE THREAD

**Issue by embix** [shanselman/SmallestDotNet#54]
> The .Net Checker application determined that you have 4.6 RC2 or greater on your machine. The application was not able to determine the exact version you have. Please log an issue including this information: releaseKey=393295 so we can get it exact in the future.

My box uses a new install of Win 10 Enterprise x64 and Vs 2015 Enterprise. I wonder why I'm not having 393297 then.

**Comment by marcosnz** [comment]
Hmmm.... the build page has been updated to say:
```
On Windows 10 systems: 393295

On all other OS versions: 393297
```
So you have the full 4.6 RTM - I will update the tool accordingly

**Comment by aloisdg** [comment]
I have the same message than @embix .

**Comment by marcosnz** [comment]
Thanks @aloisdg I think I have fixed this but waiting for it to be deployed.

**Comment by aloisdg** [comment]
Thank you for your answer :+1:
