### ISSUE TITLE
Recognize releaseKey=394254

### ISSUE THREAD

**Issue by binki** [shanselman/SmallestDotNet#64]
http://smallestdotnet.com/?releaseKey=394254

http://blogs.msdn.com/b/dotnet/archive/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1.aspx?platform=hootsuite&PageIndex=3 lists this as “394254 (Windows 10) or 394271 (All other OS versions)   .NET Framework 4.6.1”.

**Comment by SoonDead** [comment]
same

**Comment by vkstack** [comment]
How can i contribute to it.

**Comment by binki** [comment]
Looks like this was fixed by https://github.com/shanselman/SmallestDotNet/commit/f8822539144b05d3e82f2a9945fb36968d03a50a
