### ISSUE TITLE
ReleaseKey=394271

### ISSUE THREAD

**Issue by ghost** [shanselman/SmallestDotNet#67]

**Comment by rpetrusha** [comment]
,NET Checker evidently hasn't been updated to support the .NET Framework 4.6.1. The release key for WIndows 10 is 394254, and the key for all other operating systems is 394271. It recognizes neither.

**Comment by shanselman** [comment]
Adding a Description for this bug...

When someone wants to check what version of the .NET Framework they have, they can use this little utility that they run on their machine. It checks the registry for a number which is the SPECIFIC version of whatever .NET Framework you have. So 4.6 is some number and 4.6.1 is another. Every time a new version comes out we need to update the website with details on where to download it or what it is.

**Comment by apoorvnandan** [comment]
I tried to reproduce this bug. 
From what I read in the code of "Program.cs", if the release key is 394271, the program causes the user's default browser to launch and display the url "[http://smallestdotnet.com/?releaseKey=394271](http://smallestdotnet.com/?releaseKey=394271)".
On opening this url from my computer, the website says 
"_We Found .NET!
The .Net Checker application determined that you have 4.6.1 on your machine. You have 4.6.1, this is a recent version of .NET. Download an installer for the newest version .NET 4.6.1 Web._"
which is not very different from when I set release key as that of .NET Framework 4.5.1 (378758) as the corresponding url "[http://smallestdotnet.com/?releaseKey=378758](http://smallestdotnet.com/?releaseKey=378758)" says
"_We Found .NET!
The .Net Checker application determined that you have 4.5.1 on your machine._"

So, what exactly do you mean by the .NET Checker not recognizing the release keys 394254 and 394271?

**Comment by shanselman** [comment]
Here is a list of all the release keys. I (or someone) needs to update the
app to support and recognize ALL these:
https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx

On Tue, Mar 15, 2016 at 11:00 AM, Apoorv Nandan <notifications@github.com>
wrote:

> I tried to reproduce this bug.
> From what I read in the code of "Program.cs", if the release key is
> 394271, the program causes the user's default browser to launch and display
> the url "http://smallestdotnet.com/?releaseKey=394271".
> On opening this url from my computer, the website says
> "
> *We Found .NET! The .Net Checker application determined that you have
> 4.6.1 on your machine. You have 4.6.1, this is a recent version of .NET.
> Download an installer for the newest version .NET 4.6.1 Web.*"
> which is not very different from when I set release key as that of .NET
> Framework 4.5.1 (378758) as the corresponding url "
> http://smallestdotnet.com/?releaseKey=378758" says
> "
> *We Found .NET! The .Net Checker application determined that you have
> 4.5.1 on your machine.*"
>
> So, what exactly do you mean by the .NET Checker not recognizing the
> release keys 394254 and 394271?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/shanselman/SmallestDotNet/issues/67#issuecomment-196950103>
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by josedusol** [comment]
Shouldn't this be closed?. Also, from what i saw, all the others issues tagged as "first-timers-only" were resolved.
