### ISSUE TITLE
releaseKey=394806

### ISSUE THREAD

**Issue by vinipl87** [shanselman/SmallestDotNet#75]
Related to .NET 4.6.2 final version

**Comment by embix** [comment]
@vinipl87 Which version of 4.6.2 exactly?
http://referencesource.microsoft.com/dotnet462RS1.zip (.NET 4.6.2 for Win10 Aniversary)
or
http://referencesource.microsoft.com/dotnet462RTM.zip (.NET 4.6.2 for Windows 7 SP1, Windows 8.1, Windows 10, Windows Server 2008 R2 SP1, Windows Server 2012 and Windows Server 2012 R2)

**Comment by vinipl87** [comment]
I visited https://support.microsoft.com/en-us/kb/3151800 and got NDP462-KB3151800-x86-x64-AllOS-ENU.exe from link labeled "Download the Microsoft .NET Framework 4.6.2 offline installer package now." which refers to http://go.microsoft.com/fwlink/?LinkId=780600

SmallestDotNet reports that I got "4.6.2 Preview or greater" (which IMO is accurate enough), but it asks to log a issue here and thus I did :)
