### ISSUE TITLE
Exact Version 4.6.2 undeterminable

### ISSUE THREAD

**Issue by wiedemannp** [shanselman/SmallestDotNet#78]
The .Net Checker application determined that you have 4.6.2 Preview or greater on your machine. The application was not able to determine the exact version you have. Please log an issue including this information: releaseKey=394802 so we can get it exact in the future.

**Comment by fmorriso** [comment]
same for releaseKey=394806, as presented by the following PowerShell script:

Set-Location 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\V4\Full'
[PSCustomObject] $obj = Get-ItemProperty -Path . -Name @('Version', 'Release')
Write-Host ('Version={0}, Release={1}' -f $obj.Version, $obj.Release)
# consult https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx for interpretation
