### ISSUE TITLE
releaseKey=460805

### ISSUE THREAD

**Issue by rookie2531** [shanselman/SmallestDotNet#86]
http://smallestdotnet.com/?releaseKey=460805 told me to submit this issue.

Occurred after installing .NET Framework 4.7 from https://www.microsoft.com/en-us/download/confirmation.aspx?id=55170.

**Comment by feliperomero3** [comment]
Me too!
> The application was not able to determine the exact version you have. *Please log an issue including this information: **releaseKey=460805*** so we can get it exact in the future.

**Comment by FearNotDaniel** [comment]
Same here:

The .Net Checker application determined that you have 4.6.2 or greater on your machine. The application was not able to determine the exact version you have. Please log an issue including this information: releaseKey=460805 so we can get it exact in the future.
